### ISSUE TITLE
PDF opens on the last opened page instead of the page requested

### ISSUE THREAD

**Issue by superseva** [farling42/fvtt-pdf-pager#16] opened 2022-10-05 22:42 UTC
I am on Foundry 10.286. Running it on Win 10 , Node/Chrome.
Whichever method  I try (@UUID or @PDF) the requested PDF is not opening on the page value I send but it opens on wherever page it was previously closed.
I double checked to use #page=10 with a @UID, and use the |page=10 with a @PDF 
I have "Immediately Display PDF" setting ON

There are no errors in console.

**Comment by farling42** [comment] 2022-10-05 23:26
Which game system are you using?

Can you confirm that with "immediately display PDF" set to ON that the PDFs are actually opening immediately? (Just to confirm that the module is at least doing something.)

Also, are you using `@PDF` and not `@pdf` for your links?

**Comment by superseva** [comment] 2022-10-06 14:47
I am using it in Call Of Cthulhu 7e system
It does open the PDF immediately,  but it's not opening the page requested. The PDF opens on a page you closed it.
I am using @PDF as all uppercase.
I tried dragging the pdf to the journal and it correctly creates the link with page included in the link. I also tried creating it manually both with UUID links and PDF link.
Might be about the system. I'll get back home in an hour or two and I'll test it with different pdf and different system.

**Comment by farling42** [comment] 2022-10-06 23:11
It is definitely related to the CoC7 game system.
I will trace through how that system displays links to figure out why my method isn't working on CoC7 games.

**Comment by superseva** [comment] 2022-10-06 23:20
Yes, I just tested it with MYZ system since I know I don't do anything with the text enricher there and it works fine
Thanks for looking in to it

**Comment by farling42** [comment] 2022-10-06 23:35
Actually, it looks like the CoC7 game system doesn't support links connecting to sections of a Journal - this is something new in V10, but I don't know why the CoC7 game system doesn't let these work.

This is the fundamental hook which provides the capability to also choose a specific page in a PDF.

**Comment by superseva** [comment] 2022-10-06 23:45
Good catch. I opened the issue there
https://github.com/Miskatonic-Investigative-Society/CoC7-FoundryVTT/issues/1273

**Comment by farling42** [comment] 2022-10-08 22:37
Confirmed as a bug in the core coc7 with issue https://github.com/Miskatonic-Investigative-Society/CoC7-FoundryVTT/issues/1274
Fixed in next release (the one after 0.9.1)

**Closed by farling42** 2022-10-08 22:37 UTC
Labels: bug-in-core

**Comment by farling42** [comment] 2022-10-16 22:29
Fixed in coc7 system version 0.9.2
