### ISSUE TITLE
Right click on actor in actor tab not working with PDF pager module active

### ISSUE THREAD

**Issue by MagrothJ** [farling42/fvtt-pdf-pager#115] opened 2024-10-03 07:32 UTC
I just tried this with two different systems in Foundry v12, Simple worldbuilding and Pathfinder 2e. Minimal modules activated, in PF2e only libwrapper besides PDF Pager which is required. So unless it's a libwrapper problem then it's a problem with this module. 

Right click on an actor does not work. There is an error in the console.
![image](https://github.com/user-attachments/assets/ef9cdd8b-aad8-4d06-a639-ab1a2de5cff9)

**Comment by farling42** [comment] 2024-10-03 14:17
Thanks for reporting the issue. The error is definitely being generated by the PDF Pager module, but I don't understand how the situation could occur where this error would be reported.

Could you try uninstalling the pdf-pager module and reinstalling it again please. Just in case something got misconfigured somehow.

Another possibility is to check the console log to see if the pdf pager module reports any errors during world startup, which might cause the setting not to get registered.

**Comment by MagrothJ** [comment] 2024-10-03 14:49
Ok. Uninstalled and reinstalled. Same problem.
There is an error on startup though.
![bild](https://github.com/user-attachments/assets/5af1a79b-9581-4cdd-ba09-81ca2c8c60b0)

**Comment by farling42** [comment] 2024-10-03 15:00
That would be the cause.
My check for the presence of the color-picker module was wrong - this is fixed in version 1.5.2 that I've just created.

**Closed** 2024-10-03 15:01 UTC
Labels: bug

**Comment by MagrothJ** [comment] 2024-10-03 16:08
Thanks :)
